<?php
    	View::content();
    	$dataGrid = new dataGrid($items);
	$dataGrid->create = 'menus/create';
	//perfiles_id
	$dataGrid->setValue('perfiles_id', 'nombre', 'perfiles');
	$dataGrid->edit			=	$controller_name . "/edit";
	$dataGrid->delete		=	$controller_name . "/delete";
	$dataGrid->delete_confirm	=	'Desea eliminar {nombre}';
    	View::partial('datagrid/default',false,array('dataGrid'=>$dataGrid));
?>