<?php echo Tag::js('moveWin'); ?>
<style type="text/css">
<!--
.manito{cursor: pointer;}
.mover{cursor: move; }
#popup{
	border: #328AA4 4px solid;
	position: fixed;
	width: 500px;
	height: 270px;
	background-color: #fff;
	visibility: hidden;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px
	border-radius: 10px
}
#handle {
	margin:2px;
	padding:2px;
	width:578px;
	height: 10px;
	color:white;
	background-color:#328AA4;
	font-family:verdana, sans-serif;
	font-size:10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px
	border-radius: 10px	
}
#detalle{
	border: #328AA4 4px solid;
	position: fixed;
	width: 630px;
	height: 580px;
	background-color: #fff;
	visibility: hidden;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px
	border-radius: 10px
}
#div_status{
	border: #328AA4 4px solid;
	position: fixed;
	width: 364px;
	height: 560px;
	background-color: #fff;
	visibility: hidden;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px
	border-radius: 10px
}
-->
</style>
<table id="box-table-a">
	<tr>
		<th>&nbsp;</th>
		<th>Rut</th>
		<th>Nombre</th>
		<th>Factura</th>
		<th>Cuota</th>
		<th>Monto</th>
		<th>Tramo normal</th>
		<th>Fecha Venc</th>
		<th>Estado</th>
		<th>Fecha Hora</th>
		<th>Opciones</th>
	</tr>
<?php 
$i=0;
foreach($array_documentos as $documento){
	$i++;
	if($documento->tramonormal>=120){
		$tramonormal	=	'<b>' . $documento->tramonormal . '</b>';
	}else{
		$tramonormal	=	$documento->tramonormal;
	}	
	$estados			=	Load::model('estados')->find($documento->estados_id);
	$estados_nombre		=	$estados->nombre;
	$checked = false;
	if($documento->ticket=='1'){
		$checked 	=	true;
	}
	$fecha_hora				=	'';
	if($documento->fechor!=''){
		$array_fecha_hora	=	explode(' ', $documento->fechor);
		$fecha_hora			=	fsalida($array_fecha_hora[0]) . ' ' . $array_fecha_hora[1];
	}
        $rut = $documento->rut."-".$documento->dv;
	$folio = $documento->folfiscal;
	if($documento->orifac=='D'){
		$folio = Html::link('#', $documento->folfiscal, "onclick=\"verDoc($documento->id); return false;\"");
	}
?>
	<tr>
		<td id="<?php echo 'td_1_' . $documento->id ?>"><?php echo Form::check("check[$documento->id]", $documento->id, "onclick=\"cambiar(this, '$i', '$documento->id');\"", $checked)?></td>
		<td id="<?php echo 'td_2_' . $documento->id ?>"><?php echo Html::link('#', $rut, "onclick=\"verPubliguia('$rut'); return false;\""); ?></td>
		<td id="<?php echo 'td_3_' . $documento->id ?>"><?php echo Html::link('#', $documento->nombredeudor, "onclick=\"buscarMapa($documento->id); return false;\""); ?></td>
		<td id="<?php echo 'td_4_' . $documento->id ?>"><?php echo $folio; ?></td>
		<td id="<?php echo 'td_5_' . $documento->id ?>"><?php echo $documento->cuota; ?></td>
		<td id="<?php echo 'td_6_' . $documento->id ?>"><?php echo money($documento->monto); ?></td>
		<td id="<?php echo 'td_7_' . $documento->id ?>" align="center"><?php echo $tramonormal; ?></td>
		<td id="<?php echo 'td_8_' . $documento->id ?>"><?php echo fsalida($documento->fechavenc); ?></td>		
		<td id="<?php echo 'td_9_' . $documento->id ?>"><?php echo $estados_nombre ?></td>
		<td id="<?php echo 'td_10_' . $documento->id ?>"><?php echo $fecha_hora ?></td>
		<td id="<?php echo 'td_11_' . $documento->id ?>"><?php echo Html::img("aplicar.gif", null, "class=manito onclick=\"detalle($documento->id);\""); ?></td>
	</tr>
<?php } ?>
</table>

<script type="text/javascript">
for(x=1;x<<?php echo $i?>;x++){
	if(document.getElementById('check['+x+']').checked){
		cambiar(document.getElementById('check['+x+']'), x);
	}
}
function cambiar(src, id, doc) {
	id = doc;
	if (src.checked){
		for (i=1;i<12;i++){
			var elem = 'td_' + i + '_' + id;
			document.getElementById(elem).style.background	=	'#d0dafd';
			document.getElementById(elem).style.color		=	'#339';
		}
		var t = '1';
	}else{
		for (i=1;i<12;i++){
			var elem = 'td_' + i + '_' + id;
			document.getElementById(elem).style.background	=	'#e8edff';
			document.getElementById(elem).style.color		=	'#669';
		}
		var t = '0';
	}
	$.ajax({
	type: "POST",
	url: "<?php echo PUBLIC_PATH . 'calls/ticket/'; ?>",
	data: "id=" + doc + "&t="+t
	});

}
function verPubliguia(rut){
    url = "<?php echo PUBLIC_PATH . 'calls/index/'; ?>" +rut;
    $("#popup").load(url);
    $("#popup").css('visibility', "visible");
    Drag.init(document.getElementById("popup"));
}
function detalle(id){	
    url = "<?php echo PUBLIC_PATH . 'calls/viewDetails/'; ?>" +id;
    $("#div_content").load(url);    
	var theHandle = document.getElementById("handle");
	var theRoot   = document.getElementById("detalle");
	Drag.init(theHandle, theRoot);
	$("#detalle").css('visibility', "visible");
}
function verDoc(id){
    url = "<?php echo PUBLIC_PATH . 'calls/statusDoc/'; ?>" + id;
    $("#div_status").load(url);
    $("#div_status").css('visibility', "visible");
    Drag.init(document.getElementById("div_status"));
}
function buscarMapa(id){
    url = "<?php echo PUBLIC_PATH . 'calls/viewMap/'; ?>" + id;
        var window_width = 758;
        var window_height = 479;
        var newfeatures= 'scrollbars=no,resizable=no';
        var window_top = (screen.height-window_height)/2;
        var window_left = (screen.width-window_width)/2;
        window.open(url, 'Mapa','width=' + window_width + ',height=' + window_height + ',top=' + window_top + ',left=' + window_left + ',features=' + newfeatures + '');
}
</script>
<div id="detalle" style="left:20px; top:20px;">
	<div id="handle" class="mover"></div>
	<div id='div_content'></div>
</div>
<div id="div_status" class="mover"><?php echo Html::img('spin.gif'); ?></div>
<div id="popup" class="mover"><?php echo Html::img('spin.gif'); ?></div>