<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php View::content(); ?>
<?php echo Html::link($controller_name . '/logs', 'Volver', array('class' => 'nuevo')); ?>
<table class='table_grilla'>
<tr>
    <th>Nombres</th>
    <td><?php echo $usuarios->nombre; ?></td>
</tr>
<tr>
    <th>Mail</th>
    <td><?php echo $usuarios->mail; ?></td>
</tr>
<tr>
    <th>Perfil</th>
    <td><?php echo $usuarios->getPerfiles()->nombre; ?></td>
</tr>
<tr>
    <th>Entradas</th>
    <td><?php echo Html::link($controller_name . "/entradasInfo/$usuarios->id", $usuarios->entradas); ?></td>
</tr>
<tr>
    <th>Estado</th>
    <td><?php
        if($usuarios->estado=='A'){
            echo 'Activo';
        }else{
            echo 'Desactivo';
        }
        
        ?></td>
</tr>
</table>