<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php View::content(); ?>

<table class='table_grilla'>
<tr>
   <th>Usuario</th>
   <th>Fec. y hora de inicio</th>
   <th>Fec. y hora de t&eacute;rmino</th>
   <th>Tiempo</th>
   <th>Ip de acceso</th>
   <th>Perfil del usuario</th>
</tr>
<?php foreach ($items as $item):
        $aTmp_1      =   explode(" ",$item->fecha_at);
        $aTmp_2      =   explode(" ",$item->fecha_in);
        $fecha_ini   =   fsalida($aTmp_1[0])." ".$aTmp_1[1];
        $fecha_fin   =   fsalida($aTmp_2[0])." ".$aTmp_2[1];
?>
<tr>
   <td><?php echo Html::link($controller_name . '/userInfo/' . $item->usuarios_id, $item->getUsuarios()->nombre); ?></td>
   <td><?php echo $fecha_ini; ?></td>
   <td><?php echo $fecha_fin; ?></td>
   <td><?php echo restar_horas($aTmp_1[1], $aTmp_2[1])?></td>
   <td><?php echo $item->ip; ?></td>
   <td><?php echo $item->getPerfiles()->nombre; ?></td>
</tr>
<?php endforeach; ?>
</table>