<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php //echo Tag::js('jquery/jquery-ui-1.8.2.custom.min'); ?>
<?php echo Tag::js('jquery/ui/ui.datepicker'); ?>
<?php View::content(); ?>
<?php echo Form::open($controller_name . '/' . $action_name) ?>
<div align="center">
   <?php echo Calendar::text('fecha','size=10'); ?>
   <?php echo Form::submit('Ir', array('class' => 'boton'))?>
</div>
<?php echo Form::close() ?>
<table class="table_grilla">
   <tr>
   <th>NONBRES</th>
   <th>APELLIDOS</th>
   <th>PERFIL</th>
   <th>ULT. URL</th>
   <th>IP</th>
   <th>FECHA INI</th>
   <th>HORA INI</th>
   <th>FECHA FIN</th>
   <th>HORA FIN</th>
   <th>DURACION</th>
</tr>
<?php foreach($items as $item): ?>
      <tr>
         <td><?php echo $item->nombres ?></td>
         <td><?php echo $item->apellidos ?></td>
         <td><?php echo $item->perfil ?></td>
         <td><?php echo $item->url ?></td>
         <td><?php echo $item->ip ?></td>
         <td><?php echo $item->fecha_ini ?></td>
         <td><?php echo $item->hora_ini ?></td>
         <td><?php echo $item->fecha_fin ?></td>
         <td><?php echo $item->hora_fin ?></td>
         <td><?php echo $item->duracion ?></td>
      </tr>
  <?php endforeach; ?>
</table>