<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php View::content(); ?>
<?php echo Form::open() ?>
<div id="newspaper-a">
<table class="margen">
	<tr>
		<th>Menú</th>
		<td><?php echo Form::dbSelect('data.menus_id', 'nombre') ?>
        </td>	
	<tr>
		<th>Menú Flotante</th>
		<td><div id="div_controllers"></div></td>
	</tr>
	<tr>
		<th>URL</th>
		<td><?php echo Form::text('data.url');?></td>
	</tr>
	<tr>
		<th>Nombre</th>
		<td><?php echo Form::text('data.nombre');?></td>
	</tr>
	<tr>
		<th>orden</th>
		<td><?php echo Form::text('data.orden') ?></td>
	</tr>
	<tr>
		<th>Estado</th>
		<td>
		<?php echo Form::select('data.estado',  array('A'=>'Activo','D'=>'Desactivado')) ?>
        </td>	
	<tr>
		<th>&nbsp;</th>
		<td><?php echo Form::submit('Agregar') ?></td>
	</tr>
</table>
</div>
<?php echo Form::close(); ?>
<script type='text/javascript'>
$("#data_menus_id").change(function(){
    var id = $('#data_menus_id').val();
    if(id!=''){
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'menus/getMenus/'; ?>",
            data: "id=" + id,
            success: function(html){
            $("#div_controllers").html(html);
            }
        });        
    }
});
</script>
