<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php View::content(); ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('menus.id') ?>
<table class="table_forms">
	<tr>
		<th>Menú</th>
		<td><?php echo Form::text('menus.nombre') ?></td>
	</tr>
	<tr>
		<th>title</th>
		<td><?php echo Form::text('menus.title') ?></td>
	</tr>
	<tr>
		<th>&nbsp;</th>
		<td><?php echo Form::submit('Actualizar') ?></td>
	</tr>
</table>
<?php echo Form::close(); ?>