<?php
/**
 * Formulario realizado con autocarga de objeto
 * model.campo
 * 
 * Para editar la lógica es la misma en la autocarga de objeto que en este caso indicamos
 * el id del objeto y se deja oculto esto para que ActiveRecord no cree un registro nuevo
 * sino que lo actualice.
 * 
 * hidden_field_tag(array('controllers.id'))
 * 
 */
?>
<?php View::content(); ?>
<?php echo Button::link($controller_name, 'Listado'); ?>
<?php echo Form::open() ?>
<?php echo Form::hidden('controllers.id'); ?>
<div id="newspaper-a">
<table id="margen">
    <tr>
        <th>Perfil</th>
        <td><?php echo Form::dbSelect('controllers.perfiles_id', 'nombre') ?>
        </td>
    </tr>
    <tr>
        <th>Men&uacute;</th>
        <td><?php echo Form::dbSelect('controllers.menus_id', 'nombre') ?>
        </td>
    </tr>
    <tr>
        <th>URL</th>
        <td><?php echo Form::text('controllers.url', 'size=100') ?></td>
    </tr>
    <tr>
        <th>Nombre a mostrar</th>
        <td><?php echo Form::text('controllers.nombre', 'size=100') ?></td>
    </tr>
	<tr>
		<th>Orden</th>
		<td><?php echo Form::text('controllers.orden', 'size=4') ?></td>
	</tr>    
    <tr>
        <th>Estado</th>
        <td><?php echo Form::select('controllers.status', array('A'=>'Activo','D'=>'Desactivado'))?>
        </td>
    </tr>
    <tr>
        <th>&nbsp;</th>
        <td><?php echo Form::submit('Actualizar') ?></td>
    </tr>
</table>
<?php echo Form::close() ?>
<script type="text/javascript">
<?php if($reader){ ?>
$(":input").attr('disabled','disabled');
<?php } ?>
</script>