<?php
/**
 * SAV
 * PHP version 5
 * LICENSE
 *
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php
	View::content();
	echo Html::link($controller_name . '/createMain', Html::img('botones/nuevo.gif', 'Nuevo'));
	$dataGrid	=	new dataGrid($items);
	//id
	$dataGrid->ignore('id');
        //grilla
	$dataGrid->edit			=	$controller_name . "/editMain";
	$dataGrid->delete		=	$controller_name . "/deleteMain";
	$dataGrid->delete_confirm	=	'Desea eliminar {nombre}';
	View::partial('datagrid/default',false,array('dataGrid'=>$dataGrid));
?>