<?php
/**
 * Solicitudes & ordenes de compra
 * PHP version 5
 * LICENSE
 *
 * This source file is subject to the GNU/GPL that is bundled
 * with this package in the file docs/LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to fidel.oyarzo@gmail.com so we can send you a copy immediately.
 *
 * @author Fidel Oyarzo <fidel.oyarzo@gmail.com>
 */
?>
<?php View::content(); ?>
<?php echo Form::open(); ?>
<table class='table_forms'>
    <tr>
        <th>Clave actual</th>
        <td><?php echo Form::pass('data.old'); ?></td>
    </tr>
    <tr>
        <th>Nueva Clave</th>
        <td><?php echo Form::pass('data.new'); ?></td>
    </tr>
    <tr>
        <th>Repite la nueva clave</th>
        <td><?php echo Form::pass('data.rep'); ?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><?php echo Button::submit('Aceptar'); ?></td>
    </tr>
</table>
<?php echo Form::close(); ?>